### ISSUE TITLE
TODO for release

### ISSUE THREAD

**Issue by gomo** [SunriseDigital/simple-selenium-checker#1]
https://github.com/SunriseDigital/simple-selenium-checker/pull/2

- [x] Added the default timeout.
- [x] Change `nonExsits` to `notExist`
- [x] Change `like` to 'likes'
- [x] Change `equal` to `equals`
- [x] Change `by` of `checks` to `exists`
- [x] Change `body` of `checks` to `likes`
- [x] In order to unify the format of the scenario, two or more directives can not be placed in one scenario item except execif.
- [x] Change to be able to handle nested scenarios, and `execif` changes the scope to nested blocks.
- [x] Remove callback of `checks` and support the attribute check.
- [x] Implement `notExists`, `notEquals`, `notLikes` of `checks`
- [x] Change `url` of `checks` to `equals` and `likes`.
- [x] Implement checkbox, radio action
- [x] Implement select action
- [x] Implement alert and comfirm actions
- [x] Implement `{switchTo: 'frame', name: 'foobar'}`, `{switchTo: "default"}` actions
- [x] Implement to determine type automatically.
- [x] Update document.
- [x] Add mocha test sample

**Comment by gomo** [comment]
## regex for replace

```
\{(equals|notEquals|likes|notLikes|selected|unselected|checked|unchecked): *?(['"].*?['"]), *by: *By.css\((['"].*?['"])\)\}
{$1: By.css($3), value: $1}

\{(equals|notEquals|likes|notLikes|selected|unselected|checked|unchecked): *(['"].*?['"]), *type: *(\{.*?\}), *by: *By.css\((['"].*?['"])\)\}
{$1: By.css($4), type: $3, value: $2}


\{(equals|notEquals|likes|notLikes|selected|unselected|checked|unchecked): *(['"].*?['"]), *type: *(['"].*?['"])\}
{$1: $3, value: $2} 

\{(equals|notEquals|likes|notLikes|selected|unselected|checked|unchecked): *?(\[.*?\]), *by: *By.css\((['"].*?['"])\)\}
{$1: By.css($3), value: $2} 


\{(equals|notEquals|likes|notLikes|selected|unselected|checked|unchecked): *(\[.*?\]), *type: *(['"].*?['"]), *by: *By.css\((['"].*?['"])\)\}
{$1: By.css($4), type: $3, values: $2}
```

**Comment by gomo** [comment]
- [ ] waitForの引数をcheckにして名前をもう少し具体的に
